name: Go

on:
    push:
        branches: ["main"]
        tags: ["v*.*.*"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23.4"

            - name: Build
              run: make build BIN_NAME="whttp-${{github.ref_name}}"

            - uses: actions/upload-artifact@v4
              with:
                  name: whttp-${{github.ref_name}}
                  path: whttp-${{github.ref_name}}
